# Hermes Agent Configuration — global (no profile)

memory:
  memory_enabled: false
  user_profile_enabled: false

platforms:
  api_server:
    enabled: true
    key: 86d713ccfe3b4fccf555b760d84ff221355cf7f040329bfb
    port: 8642
    # Hanya izinkan tools yang aman
    # terminal, file, code_execution, memory, session_search, delegation, cronjob — DINONAKTIFKAN
    toolsets: [web, search, image_gen, tts, messaging, skills]
